CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "username" varchar(50) NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "salt" varchar(10) NOT NULL,
  "two_factor_authentication_secret" varchar(255)
);

CREATE TABLE "user_verification" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "token" varchar(10) NOT NULL,
  "expiration_date" timestamp NOT NULL,
  "is_used" boolean NOT NULL DEFAULT false
);

CREATE TABLE "team_roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "team_id" int NOT NULL,
  "user_id" int NOT NULL,
  "role_id" int NOT NULL,
  "approved_status_id" INT NOT NULL
);

CREATE TABLE "approval_statuses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar(255) NOT NULL
);

CREATE TABLE "teams" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "team_name" varchar(30) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT false,
  "date_created" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "team_members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "team_id" int NOT NULL,
  "user_id" int NOT NULL,
  "joined_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "tasks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "team_id" int NOT NULL,
  "title" varchar(128) NOT NULL,
  "description" varchar(512),
  "status_id" int NOT NULL,
  "created_by_user_id" int NOT NULL,
  "assigned_user_id" int,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "due_date" timestamp NOT NULL,
  "completed_at" timestamp
);

CREATE TABLE "task_statuses" (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "task_status_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" int NOT NULL,
  "new_status" int NOT NULL,
  "changed_by" int NOT NULL,
  "changed_at" timestamp NOT NULL DEFAULT (now())
);

